#!/bin/bash

# * Important Directory to save screenshots
screenshot_dir=~/Pictures/Screenshots

# Function to take a full-screen screenshot, show notification, and copy to clipboard
capture_fullscreen() {
    file_path="$screenshot_dir/$(date +'%Y-%m-%d_%H-%M-%S')_screenshot.png"
    maim -d 1 "$file_path"
    dunstify -a "Screenshot" -i "$file_path" "Screenshot Saved:" "$file_path"
    xclip -selection clipboard -t image/png -i "$file_path"
}

# Function to take a screenshot of a selected area, show notification, and copy to clipboard
capture_area() {
    file_path="$screenshot_dir/$(date +'%Y-%m-%d_%H-%M-%S')_screenshot.png"
    maim -d 1 -s "$file_path"
    dunstify -a "Screenshot" -i "$file_path" "Screenshot Saved:" "$file_path"
    xclip -selection clipboard -t image/png -i "$file_path"
}

# Menu options
options="Full-screen capture\nArea selection capture"

# Show the Rofi menu and capture the selected option
selected_option=$(echo -e "$options" | rofi -dmenu -p "Select an option:" -timeout 3)

# Execute the corresponding function based on the selected option
case "$selected_option" in
    "Full-screen capture") capture_fullscreen ;;
    "Area selection capture") capture_area ;;
    *) ;;
esac
