#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#	- xOnlinEx
#	- https://github.com/xOnlinEx/dotfiles
#	- xonlinex.dev@gmail.com
#

bspc monitor -d I II III IV V VI

bspc config top_padding         5
bspc config left_padding        52
bspc config right_padding       5
bspc config bottom_padding      5
bspc config border_width        0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Launch bar
eww -c "$HOME"/.config/bspwm/bar open bar &

# Launch dunst notification daemon
dunst -config "$HOME"/.config/bspwm/dunstrc &


# Fix cursor
xsetroot -cursor_name left_ptr &

# Wallpaper
nitrogen --restore &

# Launch picom
pidof -q picom || { picom --config "$HOME"/.config/bspwm/picom.conf & }

# xcorners
xcorners -W 1873 -H 1080 -x 47 -c 0d0f18ff -r 18 -b -1 &
