#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI #VII VIII IX X

bspc config bottom_padding        0
bspc config left_padding          0
bspc config right_padding         0
bspc config top_padding           30
bspc config window_gap            5
bspc config border_width          0

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore

# Fix cursor
xsetroot -cursor_name left_ptr

# Polybar
~/.config/polybar/launch.sh &

# Notification
dunst -conf ~/.config/dunst/dunstrc &

## Fix java applications
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1 &

# Picom
if ! pidof picom > /dev/null; then
    picom -b --config "$HOME"/.config/picom/picom.conf &
fi

# Polkit
if ! pidof -q polkit-gnome-authentication-agent-1 > /dev/null; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

