#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#	- xOnlinEx
#	- https://github.com/xOnlinEx/dotfiles
#	- xonlinex.dev@gmail.com
#

bspc monitor -d I II III IV V VI

bspc config top_padding         5
bspc config left_padding        60
bspc config right_padding       5 
bspc config bottom_padding      5
bspc config border_width        0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border
bspc config normal_frame_opacity 1
bspc config focused_frame_opacity 1

bspc config focused_border_color        "#78dba9"
bspc config normal_border_color         "#101419"


# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Launch bar
eww -c "$HOME"/.config/bspwm/eww/bar open bar &

# Launch dunst notification daemon
dunst -config "$HOME"/.config/bspwm/dunstrc &

# Fix cursor
xsetroot -cursor_name left_ptr &

# Wallpaper
nitrogen --restore &

# Launch picom
pidof -q picom || { picom --config "$HOME"/.config/bspwm/picom.conf & }

# Wallpaper Live
#sleep 1
#killall mpv
#xwinwrap -fs -fdt -ni -b -nf -un -o 1.0 -debug -- mpv -wid WID --loop --no-audio ~/Videos/wallpapers_live/umbrella-anime.mp4 &

# Java Aplications
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1 &
