#!/usr/bin/env bash

# Función para verificar si un elemento está en una lista
contains() {
    local e
    for e in $1; do
        [[ "$e" == "$2" ]] && return 0
    done
    return 1
}

# Función para imprimir los espacios de trabajo
print_workspaces() {
    local buf=""
    local desktops=$(bspc query -D --names)
    local focused_desktop=$(bspc query -D -d focused --names)
    local occupied_desktops=$(bspc query -D -d .occupied --names)

    for d in $desktops; do
        if contains "$focused_desktop" "$d"; then
            icon=""
            class="workspace-focused"
        elif contains "$occupied_desktops" "$d"; then
            icon=""
            class="workspace-occupied"
        else
            icon=""
            class="workspace-empty"
        fi

        buf+="(eventbox :cursor \"pointer\" (button :class \"$class\" :onclick \"bspc desktop -f $d\" \"$icon\"))"
    done

    echo "(box :orientation \"v\" :class \"works\" :halign \"center\" :valign \"center\" :space-evenly \"false\" $buf)"
}

# Imprimir los espacios de trabajo
print_workspaces

# Suscribirse a cambios en bspwm
bspc subscribe desktop node_transfer | while read -r _ ; do
    print_workspaces &
done