#!/usr/bin/env bash

# Función para verificar si un elemento está en una lista
contains() {
    local e
    for e in $1; do
        [[ "$e" == "$2" ]] && return 0
    done
    return 1
}

# Función para convertir números romanos a arábigos
roman_to_arabic() {
    local roman=$1
    case $roman in
        I) echo "1" ;;
        II) echo "2" ;;
        III) echo "3" ;;
        IV) echo "4" ;;
        V) echo "5" ;;
        VI) echo "6" ;;
        *) echo "$roman" ;;
    esac
}

# Función para obtener el número en japonés
number_in_japanese() {
    local number=$1
    case $number in
        1) echo "一" ;;
        2) echo "二" ;;
        3) echo "三" ;;
        4) echo "四" ;;
        5) echo "五" ;;
        6) echo "六" ;;
        *) echo "$number" ;;
    esac
}

# Función para imprimir los espacios de trabajo
print_workspaces() {
    local buf=""
    local desktops=$(bspc query -D --names)
    local focused_desktop=$(bspc query -D -d focused --names)
    local occupied_desktops=$(bspc query -D -d .occupied --names)

    for d in $desktops; do
        local arabic_number=$(roman_to_arabic "$d")
        local japanese_number=$(number_in_japanese "$arabic_number")
        if contains "$focused_desktop" "$d"; then
            icon="$japanese_number"
            class="workspace-focused"
        elif contains "$occupied_desktops" "$d"; then
            icon="$japanese_number"
            class="workspace-occupied"
        else
            icon="$japanese_number"
            class="workspace-empty"
        fi

        buf+="(eventbox :cursor \"pointer\" (button :class \"$class\" :onclick \"bspc desktop -f $d\" \"$icon\"))"
    done
    echo "(box :orientation \"v\" :class \"works\" :halign \"center\" :valign \"center\" :space-evenly \"false\" $buf)"
}

# Imprimir los espacios de trabajo
print_workspaces

# Suscribirse a cambios en bspwm
bspc subscribe desktop node_transfer | while read -r _ ; do
    print_workspaces &
done